const sections=["Type de contrat","Bailleur(s)","Locataire(s)","Logement","Durée","Finances","Honoraires de location","Travaux / garanties","Annexes","Avenant au contrat","Récapitulatif"];
let step=0;
const models={nu_gestion:{label:"Location nue — gestion"},nu_hors:{label:"Location nue — hors gestion"},meuble_gestion:{label:"Location meublée — gestion"},meuble_hors:{label:"Location meublée — hors gestion"}};
const blankBailleur=()=>({type:"physique",nom:"",prenoms:"",denomination:"",adresse:"",email:"",tel:""});
const blankLoc=()=>({nom:"",prenoms:"",naissance:"",lieuNaissance:"",email:"",tel:""});
const initial=()=>({type:"nu",gestion:"gestion",bailleurs:[blankBailleur()],locataires:[blankLoc()],localisation:"",habitat:"collectif",identifiantFiscal:"",regime:"copropriete",periode:"depuis2005",surface:"",pieces:"",caracteristiques:"",autresParties:"",equipements:"",chauffageMode:"individuel",chauffageAutre:"",eauMode:"individuel",eauAutre:"",destination:"habitation",professionMixte:"",accessoiresPrivatifs:"",partiesCommunes:"",technologies:"",depensesEnergie:"",anneeEnergie:"",dateEffet:"",duree:"",raisonDureeReduite:"",loyer:"",decretRelocation:"non",encadrement:"non",loyerReference:"",loyerReferenceMajore:"",loyerBase:"",complementLoyer:"",dernierLoyer:"",dateVersementDernier:"",dateDerniereRevision:"",dateRevision:"",irl:"",chargesMode:"provision",chargesMontant:"",contribution:"",justifContribution:"",assuranceColocAnnuelle:"",assuranceColocMensuelle:"",depotGarantie:"",honorairesVisiteBailleur:"",honorairesVisiteLocataire:"",honorairesEdlBailleur:"",honorairesEdlLocataire:"",travauxRecents:"",majorationTravaux:"",diminutionTravaux:"",sinistre:"non",congeLocataire:"",conditionsLocataire:"",conditionsBailleur:"",caution:"",annexes:{},avenantCharges:{},avenantInfos:{}});
let data=initial();
try{const s=localStorage.getItem("ai-location-form");if(s)data={...initial(),...JSON.parse(s)}}catch{}
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const F=(l,k,t="text",full=false)=>`<div class="field ${full?"full":""}"><label>${l}</label><input type="${t}" data-key="${k}" value="${esc(data[k])}"></div>`;
const T=(l,k)=>`<div class="field full"><label>${l}</label><textarea data-key="${k}">${esc(data[k])}</textarea></div>`;
const Sel=(l,k,opts)=>`<div class="field"><label>${l}</label><select data-key="${k}">${opts.map(([v,n])=>`<option value="${v}" ${data[k]===v?"selected":""}>${n}</option>`).join("")}</select></div>`;
function bailleursHtml(){return data.bailleurs.map((p,i)=>`<div class="box"><div class="boxhead"><strong>Bailleur ${i+1}</strong>${data.bailleurs.length>1?`<button data-rmb="${i}">Retirer</button>`:""}</div>
<label class="check"><input type="radio" name="bt-${i}" data-btype="${i}" value="physique" ${p.type==="physique"?"checked":""}>Personne physique</label>
<label class="check"><input type="radio" name="bt-${i}" data-btype="${i}" value="morale" ${p.type==="morale"?"checked":""}>Personne morale</label>
<div class="grid">${p.type==="morale"?`<div class="field"><label>Dénomination</label><input data-b="${i}:denomination" value="${esc(p.denomination)}"></div>`:`<div class="field"><label>Nom</label><input data-b="${i}:nom" value="${esc(p.nom)}"></div><div class="field"><label>Prénom(s)</label><input data-b="${i}:prenoms" value="${esc(p.prenoms)}"></div>`}
<div class="field full"><label>${p.type==="morale"?"Siège social":"Adresse"}</label><input data-b="${i}:adresse" value="${esc(p.adresse)}"></div><div class="field"><label>Email</label><input data-b="${i}:email" value="${esc(p.email)}"></div><div class="field"><label>Téléphone</label><input data-b="${i}:tel" value="${esc(p.tel)}"></div></div></div>`).join("")+`<button data-addb>Ajouter un bailleur</button>`}
function locatairesHtml(){return data.locataires.map((p,i)=>`<div class="box"><div class="boxhead"><strong>Locataire ${i+1}</strong>${data.locataires.length>1?`<button data-rml="${i}">Retirer</button>`:""}</div><div class="grid"><div class="field"><label>Nom</label><input data-l="${i}:nom" value="${esc(p.nom)}"></div><div class="field"><label>Prénom(s)</label><input data-l="${i}:prenoms" value="${esc(p.prenoms)}"></div><div class="field"><label>Date de naissance</label><input type="date" data-l="${i}:naissance" value="${esc(p.naissance)}"></div><div class="field"><label>Lieu de naissance</label><input data-l="${i}:lieuNaissance" value="${esc(p.lieuNaissance)}"></div><div class="field"><label>Email</label><input data-l="${i}:email" value="${esc(p.email)}"></div><div class="field"><label>Téléphone</label><input data-l="${i}:tel" value="${esc(p.tel)}"></div></div></div>`).join("")+`<button data-addl>Ajouter un locataire</button>`}
const annexes=["Un extrait du règlement concernant la destination de l’immeuble","Le règlement intérieur de l’immeuble","Un document informatif sur les risques de nuisances sonores aériennes","Un diagnostic de performance énergétique","Un constat de risque d‘exposition au plomb","Une copie d’un état mentionnant l’absence ou la présence de matériaux","Un état de l’installation intérieure d’électricité et de gaz","Un état des risques naturels et technologiques","Une notice d’information relative aux droits et obligations","Un état des lieux","Une autorisation préalable de mise en location","Les références aux loyers habituellement constatés","Une grille de vétusté"];
const avenantCharges=[
"L’eau (elle sera réajustée en plus ou en moins selon les consommations réelles)",
"L’électricité","Le gaz","Internet","La minuterie","Le ménage des parties communes","L’ascenseur","Le Contrat d’entretien de la chaudière"
];
const avenantInfos=[
"La taxe d’ordure ménagère sera à payer par le locataire.",
"Le compteur électrique et/ou gaz devra être ouvert au nom du locataire.",
"Le compteur d’eau devra être ouvert au nom du locataire.",
"La taxe d'habitation sera due par le locataire au 1er janvier.",
"Le locataire devra contracter une police d'assurance incendie et dégâts des eaux avant la remise des clés et s'engage à fournir au bailleur un justificatif annuel.",
"Le locataire s’engage à prendre un contrat d’entretien pour la chaudière et à fournir au bailleur un justificatif annuel.",
"Le locataire s’engage à faire un ramonage annuel de la cheminée ou du poêle à bois et à fournir au bailleur un justificatif annuel.",
"Le locataire s’engage à entretenir le jardin et les abords de la maison (pelouses, haies, plantations, terrasse)",
"Le locataire s’engage à fournir une pile pour le détecteur de fumée, lors de l’état des lieux de sortie si celle-ci ne fonctionne plus.",
"Le preneur ou locataire s’engage à prendre un contrat d’entretien pour la VMC chaque année.",
"Le preneur ou locataire s’engage à prendre un contrat d’entretien pour la pompe à chaleur chaque année"
];
function render(){ $("nav").innerHTML=sections.map((s,i)=>`<button data-step="${i}" class="${i===step?"active":""}">${i+1}. ${s}</button>`).join("");let h=`<h2>${sections[step]}</h2><p class="hint">Les données saisies servent à remplir automatiquement le bon modèle Word sans modifier ses clauses fixes.</p>`;
if(step===0)h+=`<div class="choiceGrid"><div class="box"><strong>Type de location</strong><label class="check"><input type="radio" name="type" value="nu" ${data.type==="nu"?"checked":""}>Logement nu</label><label class="check"><input type="radio" name="type" value="meuble" ${data.type==="meuble"?"checked":""}>Logement meublé</label></div><div class="box"><strong>Gestion</strong><label class="check"><input type="radio" name="gestion" value="gestion" ${data.gestion==="gestion"?"checked":""}>Gestion Action Immobilière</label><label class="check"><input type="radio" name="gestion" value="hors" ${data.gestion==="hors"?"checked":""}>Hors gestion</label></div></div><div class="notice">Modèle sélectionné : <strong>${models[data.type+"_"+data.gestion].label}</strong></div>`;
if(step===1)h+=bailleursHtml();
if(step===2)h+=locatairesHtml();
if(step===3)h+=`<div class="grid">${T("Localisation du logement","localisation")}${Sel("Type d’habitat","habitat",[["collectif","Collectif"],["individuel","Individuel"]])}${F("Identifiant fiscal du logement","identifiantFiscal")}${Sel("Régime juridique","regime",[["copropriete","Copropriété"],["monopropriete","Monopropriété"]])}${Sel("Période de construction","periode",[["avant1949","Avant 1949"],["1949-1974","1949 à 1974"],["1975-1989","1975 à 1989"],["1989-2005","1989 à 2005"],["depuis2005","Depuis 2005"]])}${F("Surface habitable (m²)","surface","number")}${F("Nombre de pièces principales","pieces","number")}${T("Caractéristiques du logement","caracteristiques")}${T("Autres parties du logement (grenier, balcon, jardin, etc.)","autresParties")}${T("Éléments d’équipement","equipements")}${Sel("Répartition du chauffage","chauffageMode",[["individuel","Individuel"],["collectif","Collectif"]])}${F("Précision chauffage / production","chauffageAutre")}${Sel("Eau chaude sanitaire","eauMode",[["individuel","Individuel"],["collectif","Collectif"]])}${F("Précision eau chaude / production","eauAutre")}${Sel("Destination","destination",[["habitation","Habitation principale"],["mixte","Habitation + professionnelle"]])}${data.destination==="mixte"?F("Profession exercée","professionMixte"):""}${T("Locaux / équipements privatifs accessoires","accessoiresPrivatifs")}${T("Parties / équipements communs","partiesCommunes")}${T("Accès technologies / communication","technologies")}${F("Dépenses énergétiques annuelles estimées","depensesEnergie")}${F("Année de référence des prix énergétiques","anneeEnergie","number")}</div>`;
if(step===4)h+=`<div class="grid">${F("Date de prise d’effet","dateEffet","date")}${F("Durée du contrat","duree")}${T("Événement / raison justifiant une durée réduite","raisonDureeReduite")}</div>`;
if(step===5)h+=`<div class="grid">${F("Loyer mensuel (€)","loyer","number")}${Sel("Décret évolution des loyers à la relocation","decretRelocation",[["non","Non"],["oui","Oui"]])}${Sel("Loyer de référence majoré applicable","encadrement",[["non","Non"],["oui","Oui"]])}${F("Loyer de référence","loyerReference")}${F("Loyer de référence majoré","loyerReferenceMajore")}${F("Loyer de base","loyerBase")}${F("Complément de loyer","complementLoyer")}${F("Dernier loyer","dernierLoyer")}${F("Date de versement du dernier loyer","dateVersementDernier","date")}${F("Date de dernière révision","dateDerniereRevision","date")}${F("Date de révision","dateRevision")}${F("Trimestre de référence IRL","irl")}${Sel("Charges récupérables","chargesMode",[["provision","Provision mensuelle"],["forfait","Forfait"],["justificatif","Remboursement sur justificatif"]])}${F("Montant des charges (€)","chargesMontant","number")}${data.type==="nu"?T("Contribution partage des économies de charges","contribution"):""}${data.type==="nu"?T("Justification de cette contribution","justifContribution"):""}${F("Assurance colocation annuelle (€)","assuranceColocAnnuelle","number")}${F("Assurance colocation mensuelle (€)","assuranceColocMensuelle","number")}</div>`;
if(step===6){
  const totalB=(Number(data.honorairesVisiteBailleur)||0)+(Number(data.honorairesEdlBailleur)||0);
  const totalL=(Number(data.honorairesVisiteLocataire)||0)+(Number(data.honorairesEdlLocataire)||0);
  h+=`<div class="notice">Montants repris automatiquement dans le tableau « Honoraires de location » du Word.</div><div class="grid">${F("Visite, constitution du dossier et rédaction — Bailleur (€)","honorairesVisiteBailleur","number")}${F("Visite, constitution du dossier et rédaction — Locataire (€)","honorairesVisiteLocataire","number")}${F("État des lieux d’entrée — Bailleur (€)","honorairesEdlBailleur","number")}${F("État des lieux d’entrée — Locataire (€)","honorairesEdlLocataire","number")}<div class="field"><label>Total bailleur</label><input value="${totalB.toFixed(2)} €" readonly></div><div class="field"><label>Total locataire</label><input value="${totalL.toFixed(2)} €" readonly></div></div>`
}
if(step===7)h+=`<div class="grid">${F("Dépôt de garantie (€)","depotGarantie","number")}${T("Travaux récents / mise en conformité","travauxRecents")}${T("Majoration de loyer liée à des travaux","majorationTravaux")}${T("Diminution de loyer liée à des travaux","diminutionTravaux")}${Sel("Sinistre indemnisé catastrophe naturelle / technologique","sinistre",[["non","Non"],["oui","Oui"]])}${F("Date de congé du locataire en place","congeLocataire","date")}${T("Conditions particulières / obligations locataire","conditionsLocataire")}${T("Conditions particulières / obligations bailleur","conditionsBailleur")}${T("Caution solidaire","caution")}</div>`;
if(step===8)h+=`<div class="notice">Coche uniquement les annexes effectivement jointes au bail.</div><div class="grid">${annexes.map(a=>`<label class="check"><input type="checkbox" data-annexe="${esc(a)}" ${data.annexes[a]?"checked":""}>${a}</label>`).join("")}</div>`;
if(step===9)h+=`<div class="notice">Ces cases correspondent à la page « AVENANT AU CONTRAT DE LOCATION » du modèle Word.</div><div class="section">La provision sur charges comprend</div><div class="grid">${avenantCharges.map(a=>`<label class="check"><input type="checkbox" data-avcharge="${esc(a)}" ${data.avenantCharges[a]?"checked":""}>${a}</label>`).join("")}</div><div class="section">Informations diverses</div><div class="grid">${avenantInfos.map(a=>`<label class="check"><input type="checkbox" data-avinfo="${esc(a)}" ${data.avenantInfos[a]?"checked":""}>${a}</label>`).join("")}</div>`;
if(step===10){const b=data.bailleurs.map(p=>p.type==="morale"?p.denomination:[p.nom,p.prenoms].filter(Boolean).join(" ")).filter(Boolean).join(", "),l=data.locataires.map(p=>[p.nom,p.prenoms].filter(Boolean).join(" ")).filter(Boolean).join(", ");h+=`<div class="notice">Le bouton « Générer le Word » utilisera automatiquement <strong>${models[data.type+"_"+data.gestion].label}</strong>.</div><div class="box"><strong>Bailleur(s)</strong><p>${esc(b||"Non renseigné")}</p><strong>Locataire(s)</strong><p>${esc(l||"Non renseigné")}</p><strong>Logement</strong><p>${esc(data.localisation||"Non renseigné")}</p><strong>Loyer</strong><p>${esc(data.loyer||"Non renseigné")} €</p></div>`}
$("content").innerHTML=h;bind()}
function bind(){document.querySelectorAll("[data-step]").forEach(x=>x.onclick=()=>{step=+x.dataset.step;render()});document.querySelectorAll("[data-key]").forEach(x=>x.oninput=x.onchange=()=>{data[x.dataset.key]=x.value;if(["destination"].includes(x.dataset.key))render()});document.querySelectorAll('input[name="type"]').forEach(x=>x.onchange=()=>{data.type=x.value;render()});document.querySelectorAll('input[name="gestion"]').forEach(x=>x.onchange=()=>{data.gestion=x.value;render()});document.querySelectorAll("[data-b]").forEach(x=>x.oninput=()=>{const[i,k]=x.dataset.b.split(":");data.bailleurs[+i][k]=x.value});document.querySelectorAll("[data-btype]").forEach(x=>x.onchange=()=>{data.bailleurs[+x.dataset.btype].type=x.value;render()});document.querySelectorAll("[data-l]").forEach(x=>x.oninput=()=>{const[i,k]=x.dataset.l.split(":");data.locataires[+i][k]=x.value});document.querySelectorAll("[data-addb]").forEach(x=>x.onclick=()=>{data.bailleurs.push(blankBailleur());render()});document.querySelectorAll("[data-addl]").forEach(x=>x.onclick=()=>{data.locataires.push(blankLoc());render()});document.querySelectorAll("[data-rmb]").forEach(x=>x.onclick=()=>{data.bailleurs.splice(+x.dataset.rmb,1);render()});document.querySelectorAll("[data-rml]").forEach(x=>x.onclick=()=>{data.locataires.splice(+x.dataset.rml,1);render()});document.querySelectorAll("[data-annexe]").forEach(x=>x.onchange=()=>data.annexes[x.dataset.annexe]=x.checked);document.querySelectorAll("[data-avcharge]").forEach(x=>x.onchange=()=>data.avenantCharges[x.dataset.avcharge]=x.checked);document.querySelectorAll("[data-avinfo]").forEach(x=>x.onchange=()=>data.avenantInfos[x.dataset.avinfo]=x.checked)}
function dbOpen(){return new Promise((res,rej)=>{const q=indexedDB.open("action-immo-location-models",1);q.onupgradeneeded=()=>q.result.createObjectStore("files");q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putFile(key,file){const db=await dbOpen(),bytes=new Uint8Array(await file.arrayBuffer());return new Promise((res,rej)=>{const tx=db.transaction("files","readwrite");tx.objectStore("files").put({name:file.name,bytes},"model_"+key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getFile(key){try{const db=await dbOpen();return await new Promise((res,rej)=>{const tx=db.transaction("files","readonly"),q=tx.objectStore("files").get("model_"+key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}catch{return null}}
async function renderTemplates(){let h="";for(const [k,v] of Object.entries(models)){const f=await getFile(k);h+=`<div class="templateRow"><div><strong>${v.label}</strong><small>${f?'<span class="ready">Modèle chargé : '+f.name+'</span>':'<span class="missing">Modèle à charger</span>'}</small></div><div><button data-load="${k}">${f?"Remplacer":"Charger"}</button><input type="file" accept=".docx" id="file-${k}"></div></div>`} $("templates").innerHTML=h;document.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>document.getElementById("file-"+b.dataset.load).click());for(const k of Object.keys(models)){const inp=document.getElementById("file-"+k);inp.onchange=async()=>{if(!inp.files[0])return;await putFile(k,inp.files[0]);$("status").textContent="Modèle enregistré";await renderTemplates()}}}
$("modelsBtn").onclick=async()=>{$("modelsModal").classList.remove("hidden");await renderTemplates()};$("closeModels").onclick=()=>$("modelsModal").classList.add("hidden");
$("saveBtn").onclick=()=>{localStorage.setItem("ai-location-form",JSON.stringify(data));$("status").textContent="Dossier sauvegardé localement"};
$("generateBtn").onclick=async()=>{try{const key=data.type+"_"+data.gestion,f=await getFile(key);if(!f){$("modelsModal").classList.remove("hidden");await renderTemplates();alert("Charge d’abord le modèle Word : "+models[key].label);return}localStorage.setItem("ai-location-form",JSON.stringify(data));const bytes=f.bytes instanceof Uint8Array?f.bytes:new Uint8Array(f.bytes),blob=await buildLocation(bytes,data),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="CONTRAT_LOCATION_"+data.type.toUpperCase()+"_"+(data.gestion==="gestion"?"GESTION":"HORS_GESTION")+"_REMPLI.docx";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert("Impossible de générer le Word : "+e.message)}};
$("prev").onclick=()=>{if(step>0){step--;render()}};$("next").onclick=()=>{if(step<sections.length-1){step++;render()}};
render();